[package]
name = "day_03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_03_part_01"
path = "src/part_01.rs"

[[bin]]
name = "day_03_part_02"
path = "src/part_02.rs"

[dependencies]
utils = { path = "../utils" }